### PR TITLE
Include timestamp in allowed field list for filters + other improvements

### LINKED ISSUE #14: Unable to filter by timestamp
timestamp is not recognized as a valid field for filtering

### PR DESCRIPTION
**Pull request by ozroc**
Fixes #14

### CODE REVIEW

**Comment by ozroc** [comment]
This PR implements:

* Filtering by timestamp
* Client-side sorting
* Autodiscovery of field list
* Usage of complex data structures (such as dictionaries, lists or even complex numbers) for values

**Comment by ozroc** [comment]
* Modularized encoders. Extensible encoders can be used. By default json serializer is used, but also included a complex number encoder (as an example) and a null one to get original behaviour  (only strings and numbers allowed as values).
* Use of json configuration file (as generated during stream creation) and make variable names consistent with json file's one.
* Some additional code refactorization is also present.

**Comment by matze** [comment]
Looks good to me :+1:

However, for the sake of a clean history, I'd suggest to squash your changes down to a few relevant commits. Especially, the "Merge branch" commits do look somewhat confusing.

**Comment by ozroc** [comment]
You're true, my commit history is full of trash. :+1: 

OK, I've squashed my ugly commits and tried to let only meaningful ones.

**Comment by matze** [comment]
Thanks!

**Pull request merged**
